name = "BasicVectorOps"
uuid = "b71de934-a06d-437f-8687-abcffcaf83f4"
authors = ["Brady Elster"]
version = "1.0.0-DEV"

[compat]
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
